Port qt6
fenuks/cantata pull request #1
Opened 2024-02-18 18:35 UTC by ochurlaud

I'll cleanup  when it compiles and when I can test it (70% or so currently)

2024-02-23 13:11 UTC, ochurlaud commented on models/playlistsmodel.cpp
> +            QVariant var = QVariant::fromValue<Song>(*s);
sholud be setValue(*s)

2024-02-23 13:11 UTC, ochurlaud commented on models/playqueuemodel.cpp
> +        QVariant var = QVariant::fromValue<Song>(s);
var.setValue(s)

2024-02-23 13:11 UTC, ochurlaud commented on models/streamsearchmodel.cpp
> +                list << StreamsModel::self()->addBookmarkAct();
setValue()

2024-02-23 13:11 UTC, ochurlaud commented on models/streamsearchmodel.cpp
> +            QVariant v = QVariant::fromValue<QList<Action *> >(list);
setValue()

2024-02-23 13:11 UTC, ochurlaud commented on gui/mainwindow.cpp
> +    QList<int> seekShortcuts=QList<int>() << (int)Qt::CTRL << (int)Qt::SHIFT << (int)(Qt::CTRL|Qt::SHIFT);
Come back to Modifier keys

2024-02-23 13:11 UTC, ochurlaud commented on gui/mainwindow.cpp
> +    clearPlayQueueAction->setShortcut(Qt::CTRL|Qt::Key_K);
Come back to Modifier keys

2024-02-23 13:11 UTC, ochurlaud commented on models/actionmodel.cpp
> +        QList<Action *> list;
back to v.setValue()

2024-02-29 21:09 UTC, ochurlaud commented
Compiled and tested on Linux: it plays remote music and can read streams (I don't use everything so someone should make some deeper tests). The connections to wikipedia and co work fine.

2024-02-29 21:10 UTC, ochurlaud commented
@fenuks do you think you would test and merge in your repo, or should I merge that to my "main" branch ?

2024-03-01 00:25 UTC, fenuks commented
Yes, thank you for the effort. I was planning to do Qt6 migration myself soon, because I am already using Plasma 6. I will try to check your code this weekend.

2024-05-21 03:11 UTC, nullobsi commented
I've also been doing some work on [nullobsi/cantata](https://github.com/nullobsi/cantata) to modernize the build scripts based on this PR.

2024-05-22 20:43 UTC, ochurlaud commented
@fenuks  any news ?

2024-11-10 11:17 UTC, fenuks requested changes
Hello, sorry for the very long hiatus.

This PR looks very good, clean & lean. Everything seems to work, I tried every feature that I could.

There are few minor issues:
1. Could you add this patch? Without it, cantata doesn't compile (xml changes), and immediately crash after startup (cpp change). There is also change for PKGBUILD file.
```diff
diff --git i/PKGBUILD w/PKGBUILD
index ffe4a0efd..d9d06d4ed 100644
--- i/PKGBUILD
+++ w/PKGBUILD
@@ -13,8 +13,8 @@ depends=(
   libmtp
   libmusicbrainz5
   mpg123
-  qt5-multimedia
-  qt5-svg
+  qt6-multimedia
+  qt6-svg
   taglib
   libebur128
   ffmpeg
diff --git i/dbus/notify.cpp w/dbus/notify.cpp
index 23d2fbde8..bdf40b1f3 100644
--- i/dbus/notify.cpp
+++ w/dbus/notify.cpp
@@ -61,7 +61,7 @@ QDBusArgument& operator<< (QDBusArgument &arg, const QImage &image)
     arg.beginStructure();
     arg << i.width();
     arg << i.height();
-    arg << i.bytesPerLine();
+    arg << static_cast<int>(i.bytesPerLine());
     arg << i.hasAlphaChannel();
     int channels = /*i.isGrayscale() ? 1 : */ (i.hasAlphaChannel() ? 4 : 3);
     arg << i.depth() / channels;
diff --git i/dbus/org.gnome.SettingsDaemon.MediaKeys.xml w/dbus/org.gnome.SettingsDaemon.MediaKeys.xml
index ba9b084c6..9caf240f5 100644
--- i/dbus/org.gnome.SettingsDaemon.MediaKeys.xml
+++ w/dbus/org.gnome.SettingsDaemon.MediaKeys.xml
@@ -15,4 +15,3 @@
     </signal>
   </interface>
 </node>
-"
diff --git i/dbus/org.gnome.SettingsDaemon.xml w/dbus/org.gnome.SettingsDaemon.xml
index 9e5f2d323..8cafc94fa 100644
--- i/dbus/org.gnome.SettingsDaemon.xml
+++ w/dbus/org.gnome.SettingsDaemon.xml
@@ -12,4 +12,3 @@
     </signal>
   </interface>
 </node>
-"
```
2. README needs to be updated, it has references to Qt5.
3. I've added one commit fixing building – migrating from deprecated ffmpeg function call

2024-11-10 11:17 UTC, fenuks commented on cmake/FindTaglib.cmake
> +    execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} --modversion taglib RESULT_VARIABLE _return_VALUE OUTPUT_VARIABLE TAGLIB_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
This line is overindented.

2024-11-10 11:17 UTC, fenuks commented on gui/mainwindow.cpp
> +    expandAllAction->setShortcut(Qt::ControlModifier | Qt::Key_Down);
In some places there are no spaces added around `|`. Generally I think this version is more readable, but it has to be consistent with rest of the code, at least within file. Grepping shows that version without spaces is two times more common.

2024-11-10 11:17 UTC, fenuks commented on CMakeLists.txt
> +    include(DeployQt6)
I don't use Mac, but this might be wrong. There is `cmake/DeployQt5.cmake` file which is to be removed. There is no `DeployQt6.cmake` file, so this probably will fail.

2024-11-12 18:28 UTC, ochurlaud commented
It seams to me that https://github.com/nullobsi is way ahead and should be considered instead.

2024-11-12 23:21 UTC, fenuks commented
I'll keep an eye on it, but it's still too early to judge whether it will get maintained for the foreseeable future. If it does, I'll switch, but for now I indent to keep my version working, and from time to time add some improvement based on my needs. From what I can see, perhaps 90% of changes in nullobsi version are related to building and other minor changes.

2025-01-26 10:29 UTC, fenuks commented
I merged this changes with some minor changes. Thank you again for your work.

2025-01-26 10:29 UTC, closed without merging

2025-02-04 20:36 UTC, a17r commented
@fenuks do you plan to "play real upstream" by spinning releases in the future?

2025-02-04 21:50 UTC, fenuks commented
> do you plan to "play real upstream" by spinning releases in the future?

This fork is mainly for my own purposes, I don't know if anybody else uses it. I don't need new releases. I use git version, but if it would make other people's lives easier, then why not. Generally, it's a low-effort fork, I don't want give a wrong idea – cantata works fine for me as it is, so I don't see need for major changes. There is https://github.com/nullobsi/cantata fork that is more active, but last time I checked, it didn't contain changes I would be interested in. I have some ideas for small improvements to be added in future, like option to copy selected songs metadata or more options to move songs in a queue.